### ISSUE TITLE
Add Gradualizer to the list

### ISSUE THREAD

**Issue by erszcz** [llaisdy/beam_languages#18]
While not a separate language, [Gradualizer](https://github.com/josefs/Gradualizer) seems to be in the scope of this list of projects. It's a gradual typing system and static code analysis tool for Erlang.

It works blazingly fast in comparison with Dialyzer. The type system, IMHO, also seems more intuitive to work with - it's based on the following paper, which extends simply typed lambda calculus - http://scheme2006.cs.uchicago.edu/13-siek.pdf.

**Comment by llaisdy** [comment]
Thanks very much for the alert!  This will fit very nicely in the "Erlang and Types" section.  I'll add it just now.

**Comment by llaisdy** [comment]
Added.  See commit 6b21d12.
