### ISSUE TITLE
Add Caramel

### ISSUE THREAD

**Issue by hyphenrf** [llaisdy/beam_languages#23]
It's an exciting new project that compiles plain OCaml to Erlang: https://github.com/AbstractMachinesLab/caramel

**Comment by llaisdy** [comment]
Thank you very much!  Yes, that does look exciting!

**Comment by llaisdy** [comment]
Done: https://github.com/llaisdy/beam_languages/commit/5d0ec5b59b05fa2280dfe51e5e2eeb88048c23d8
