### ISSUE TITLE
BEAM spec

### ISSUE THREAD

**Issue by Neftedollar** [llaisdy/beam_languages#8]
Hi? do you know where can I find something about BEAM for add another lang in  your list)

**Comment by llaisdy** [comment]
Sorry I don't understand your question.  BEAM is the virtual machine that erlang runs on.

**Comment by Neftedollar** [comment]
Sorry, I mean something about BEAM specification.

**Comment by llaisdy** [comment]
Good question.  I can only suggest the talks in the [About Languages](https://github.com/llaisdy/beam_languages#about-languages) section, or this SO q&a:

http://stackoverflow.com/questions/38757864/where-can-i-get-the-latest-specification-of-erlang-beam-vm

**Comment by Neftedollar** [comment]
tank you.
